[theme]
primaryColor = "#00D4FF"             # Electric Cyan
backgroundColor = "#121212"          # Dark Background
secondaryBackgroundColor = "#1E1E2F" # Slightly Lighter Dark
textColor = "#E6E6E6"                # Light Gray
font = "Poppins"                     # Or another sans-serif font
